name: Django CI

on:
  push:
    branches-ignore:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install black
        run: python -m pip install black
      - name: Run Black Check
        run: black --check .
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: "Create .env file"
        run: |
          touch .env
          TVD_API_URL
          echo TVD_API_KEY=${{ secrets.API_KEY }} >> .env
          echo TVD_API_HOST=${{ secrets.API_KEY }} >> .env
      - name: Run Check
        run: |
          python manage.py check
          python manage.py test
